FROM debian:jessie
MAINTAINER dev+docker@wazo.community

ENV DEBIAN_FRONTEND noninteractive

RUN true && \
    apt-get -q update && \
    apt-get -q -y install apt-utils \
                          gdb \
                          libc6-dbg \
                          wget && \
    true

WORKDIR /usr/src
RUN echo "deb http://mirror.wazo.community/archive/ wazo-${WAZO_VERSION} main" >> /etc/apt/sources.list.d/wazo-dist.list
RUN wget http://mirror.wazo.community/wazo_current.key -O - | apt-key add -
RUN true && \
    apt-get -q update && \
    apt-get -q -y install asterisk \
                          asterisk-dbg \
                          xivo-libsccp \
                          xivo-libsccp-dbg && \
    apt-get -q source asterisk && \
    true

CMD ["gdb", "asterisk", "/core"]
