#!/bin/bash -e

wazo_version=$1
core_file=$2

if [ -z "$wazo_version" -o -z "$core_file" ] ; then
    echo "Usage: $0 <wazo_version> <core_file>"
    exit 1
fi

extract_asterisk_sources() {
    destination=$1
    rm -rf "${destination}"
    container_id=$(docker create "wazopbx/wazo-asterisk-gdb:${wazo_version}")
    docker cp "${container_id}:/usr/src/" "${destination}"
    docker rm "${container_id}"
}

debian_distribution() {
    local wazo_version=$1
    if [ "${wazo_version}" \< "18.01" ] ; then
        echo "jessie"
    elif [ "${wazo_version}" \< "19.13" ] ; then
        echo "stretch"
    else
        echo "buster"
    fi
}

cat Dockerfile-gdb.tpl | sed "s/\${WAZO_VERSION}/${wazo_version}/; s/\${DEBIAN_DISTRIBUTION}/$(debian_distribution ${wazo_version})/" | docker build -t "wazopbx/wazo-asterisk-gdb:${wazo_version}" -

mkdir -p sources
extract_asterisk_sources "sources/wazo-${wazo_version}"

docker run -it -v "${core_file}:/core" "wazopbx/wazo-asterisk-gdb:${wazo_version}"
