#!/bin/bash

set -ex

python3 -m venv .venv

. .venv/bin/activate

pwd
ls -l

cd $SRCDIR

pip install -r integration_tests/test-requirements.txt

cd integration_tests

make test-setup
make test

# integration-tests ends here
