#!/bin/sh

cd

git clone https://gerrit.asterisk.org/testsuite

cd testsuite

cd asttest
make
make install

cd ..

cd addons
make update
cd starpy
sudo python setup.py install

cd ~/testsuite

./runtests.py

# testsuite.sh ends here
