#! /bin/sh
# Copyright 2020-2024 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

###############find $dir -name 'agi-bin' -prune -o -type f#####################
# If asterisk in running, reload it
if [ -f "/lib/systemd/system/asterisk.service" ];then
	if [ -f /run/asterisk/asterisk.pid ];then
		deb-systemd-invoke reload asterisk || exit $?
	fi
fi
