usr/sbin
usr/lib/libasterisk*
usr/share/asterisk/firmware
usr/share/asterisk/keys
usr/share/asterisk/conf
usr/share/asterisk/documentation
usr/share/asterisk/rest-api

usr/lib/asterisk
usr/share/asterisk/keys /var/lib/asterisk/
usr/share/asterisk/static-http
var/lib/asterisk/documentation/thirdparty /usr/share/asterisk/documentation/

debian/asterisk.service lib/systemd/system/
debian/asterisk_fix /usr/share/asterisk/bin/
